default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  redis:
    host: <%= ENV["REDIS_HOSTNAME"] %>
    port: 6379
    db: 0
    options:
      namespace: store-dev

development:
  <<: *default
  database: store_development

production:
  <<: *default
  database: store_production

test:
  <<: *default
  database: store_test
